"use strict";
import "nodelist-foreach-polyfill";
import "@babel/polyfill";
import elementClosest from "element-closest";
elementClosest(window);
import "formdata-polyfill";
import "es6-promise";
import "fetch-polyfill";
import smoothscroll from "smoothscroll-polyfill";
smoothscroll.polyfill();

import paralax from "./modules/paralax";
import burgerMenu from "./modules/burgerMenu";
import resizeWin from "./modules/resizeWin";
import chengeColorSelect from "./modules/chengeColorSelect";
import activateSecondForm from "./modules/activateSecondForm";
import calc from "./modules/calc";
import calculateActive from "./modules/calculateActive";
import openQuiz from "./modules/openQuiz";
import chengeTab from "./modules/chengeTab";
import chengeTabMobile from "./modules/chengeTabMobile";
import validate from "./modules/validate";
import smoothScroll from "./modules/smoothScroll";
import openModal from "./modules/openModal";
import openModalContacts from "./modules/openModalContacts";

paralax();
burgerMenu();
resizeWin();
chengeColorSelect();
activateSecondForm();
calc();
calculateActive();
openQuiz();
chengeTab();
chengeTabMobile();
validate();
smoothScroll();
openModal();
openModalContacts();
